### ISSUE TITLE
Assign sequential HRU ID numbers tool - the new grid doesn't have an attribute table

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis-h#10]
Please build the attribute table of the output grid. When an HRU grid doesn't have an attribute table, the HRU cannot be used in subsequent processes.

**Comment by lbross** [comment]
Can you provide an example AOI? This may have happened due to an error when the sequential id tool ran rather than a missing step with the tool itself.

**Comment by lbross** [comment]
Fixed multiple bugs with sequential id tool in release 1.6.0. Not able to recreate this particular bug.
