### ISSUE TITLE
Raster slice tool

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis-h#16]
When configuring the raster slice tool, BAGIS-H shows a warning message if a continuous raster is selected for example. For example, the filled DEM. Should the slice tool show this warning? It seems that the slice tool is intended to be used on continuous rasters.

**Comment by jdduh** [comment]
Yes, slice can be used on continuous rasters. It seems the tool also works on discrete rasters (e.g., HRU layers). Please remove the warning message and allow the tool to operate on continuous rasters.

**Comment by lbross** [comment]
Fixed in version 1.6.0 on issue_15 branch
