### ISSUE TITLE
Need to store the smallest polygon size for non contiguous HRU datasets

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis-h#17]
There is a need to display the size of the smallest polygon in an HRU dataset on the Eliminate form and on the BAGIS-P Export Parameters form. For non-contiguous HRU datasets, this could require using the multipart to singlepart GP tool to disassemble multipart features. This GP tool is slow and would take too much time to run when loading the aforementioned forms. Some other options:

1. Add the minimum polygon size as a field on the hru log.xml. We can calculate this field before dissolving grid_v to create the non-contig HRU dataset. How to handle HRU's created before we added this field?

2. Query polygrid_v for the smallest polygon size. This vector is created before dissolving grid_v to create the non-contig HRU dataset. Query performance should be good. We would need to add this to the list of layers that are archived in eBAGIS since we'd now be using it.

3. Query the grid for the minimum count and multiply it by the cell size to get the smallest area. Performance should be good. Not sure about accuracy compared to polygon size.

**Comment by jdduh** [comment]
Option 3 won't work because non-contiguous HRU cells have the same gridcode value. The count value represents the HRU area, not the individual polygon area.

Option 1 suffers from backward compatibility issue - not good.

Option 2 seems the most feasible. Does every HRU have a polygrid_v layer? If so, then you should be able to query the stats of the shape_area (or whatever area field BAGIS-H has generated) field and get the minimum value.

**Comment by lbross** [comment]
Every non-contiguous HRU has a polygrid_v layer. We save off the original grid_v as polygrid_v which is generated by converting the grid to polygons before dissolving it to create the non-contiguous HRU. We will need to have Jarrett archive polygrid_v so it is always present, even on downloaded HRU datasets.

I will check for the presence of polygrid_v and use it. If it is missing, I will use grid_v.

**Comment by lbross** [comment]
Unfortunately polygrid_v does not contain the "AREA_SqKm" and "AREA_Acre" columns that are maintained by BAGIS-H on grid_v. I will see if AREA_SqKm can be calculated on the fly to display the area on the forms.

**Comment by jdduh** [comment]
You can query the stats on the shape_area field (i.e., find the minimum value) and then convert that value to km^2 or acre. You will need to know the horizontal coordinate unit (meter or feet) of the vector layer to perform the conversion correctly.

**Comment by lbross** [comment]
Added min polygon size to BAGIS-P Export Parameters form. The units used are dependent on the linear unit of the DEM since this is queried when the AOI is selected. If the DEM is in feet, min poly size displays in acres, otherwise square kilometers. This issue can be closed when BAGIS-H and BAGIS-P are released as the field has been added to both eliminate and export forms.

**Comment by lbross** [comment]
Fixed in BAGIS-H v1.6.1
