### ISSUE TITLE
BAGIS-H and -P try to define the unit of the PRISM precipitation layers when they don't exist

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis-h#19]
BAGIS V2 allows users to create an AOI without clipping the PRISM precipitation layers (17 of them) to the AOI. When opening the AOIs without PRISM layers in BAGIS-H or BAGIS-P, the set unit dialog window shows up. It doesn't create any problem for BAGIS-H/-P execution, but create a lot of confusion for the users.

**Comment by lbross** [comment]
What is the desired behavior in this case? Should the set unit dialog for precipitation units be suppressed if there is no prism.gdb?

**Comment by jdduh** [comment]
Yes, please suppress the dialog when there is no prism.gdb.

**Comment by lbross** [comment]
This is fixed in BAGIS-H and BAGIS-P. Verified that BAGIS V2H only uses elevation units so it is not affected.

**Comment by lbross** [comment]
Fixed in BAGIS-H v1.6.1
