### ISSUE TITLE
AOI Upload: What to do with extra data layers in hru.gdb

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis-h#2]
The hru.gdb contains data layers that we don't want to upload to the central database. The limited functionality of the ArcGIS Zip API allows zipping of folders but not adding or removing single files from a folder. Although the service will ignore extraneous files, we don't want to take extra time to upload unnecessary files.

Can the upload service have some conditional logic to look for files normally in the hru.gdb folder in a folder of a different name? Perhaps _hru.gdb?

Do we need to retain these extra files when generating hrus in BAGIS-H? How about putting them in a separate archive.gdb under the HRU folder? This only effects HRU's going forward.
1. oldgrid: Created by the sequential id tool. User has option of retaining a copy of the original dataset
2. polygrid_v: Generated when creating a non-contiguous set of HRU's
3. r00x:  output of each of the rules that was used to generate the HRU's

**Comment by jdduh** [comment]
oldgrid, polygrid_v, r00x will not be uploaded to the server repository. The HRU.gdb is duplicated first and then unused files removed before the gdb is compressed and uploaded. The duplicated gdb is removed from the desktop harddrive after the upload is finished.

**Comment by lbross** [comment]
Issue references PSU-CSAR/django-ebagis#3

A new, empty .gdb will be created and named "_HRU.gdb" where HRU is the HRU name. The desired files will be added to this .gdb before it is zipped up and included with the aoi upload. The original HRU.gdb won't be uploaded. "_HRU.gdb" will be deleted after the upload is sent to the web service. The extra files will remain in their original location in the HRU.gdb.

The web service will need to be updated to check for geodatabase names that start with _ and to handle them the same as HRU.gdb coming from the web client.

**Comment by lbross** [comment]
Works against test.ebagis
