### ISSUE TITLE
Raster reclass (discrete data) - no apply button on the define rule dialog

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis-h#20]
The dialog window is not resizable and the Apply button cannot be found on the dialog.

**Comment by lbross** [comment]
This is related to issue #21. The apply button is not visible if the user uses a larger font size. Updated all HRU rules forms so that they are now resizable.

**Comment by lbross** [comment]
Forms with problems due to font size: Eliminate, Try dpi solution.
