### ISSUE TITLE
Font size issue on esriaddin GUI

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/vb-bagis-h#21]
This is a general issue related to BAGIS(-H/-P). When users set their windows font size to large (e.g., 150%), the captions (texts) on button faces and text labels become obscured. For some dynamic forms (e.g., BAGIS-P method editor), the controls are displaced (see image).

![displaced gui](https://cloud.githubusercontent.com/assets/11510708/11414875/d1c48abe-93af-11e5-80f2-28e29cbb1ed9.JPG)

This is not a new issue, but has become a concern for NWCC users. They recently upgraded their computers. The new computers come with super high resolutions, forcing the "older" users to increase the font size.

**Comment by jdduh** [comment]
Here is a suggested solution.

http://through-the-interface.typepad.com/through_the_interface/2011/03/handling-dpi-scaling-in-your-net-applications-forms.html

**Comment by lbross** [comment]
The form pictured above is generated dynamically depending on how many data sources need to be configured. I tried the suggested solution with this form and it didn't help. I think Windows tries to fit the controls on the form as best it can but this fails when the controls are place programmatically. Only solution I can think of in this case is to change the dropdowns to a grid, although we haven't used dropdowns "in" a grid before.

Development for this issue is further complicated because I can't change the font size on the remote computer I am developing on.

**Comment by lbross** [comment]
Another possibility for this particular form is to decide on a pre-determined maximum number of data sources. The fields could be added to the form at start-up and hidden if they are not needed. We could put a check in to warn the user if the model needed more than the maximum number of data sources.

**Comment by lbross** [comment]
Set-up six possible data sources. Warn if number is exceeded.

**Comment by lbross** [comment]
I re-designed the eliminate form today to accommodate larger fonts. I also experimented with the font vs dpi scaling as suggested by an earlier comment. The form looks the same in the large font with both methods but very different with small fonts. The dpi method consolidates the form so the layout is similar to large fonts but leaves a bunch of space around the edge. Posting example images here. Thoughts on which autoscale mode to use?

mode: dpi, font-size: small
![dpi_small](https://cloud.githubusercontent.com/assets/11527966/11548270/6603b998-990f-11e5-8cf1-c30ef6f18ef9.jpg)

mode: font, font-size: small
![font_small](https://cloud.githubusercontent.com/assets/11527966/11548280/7f8fd608-990f-11e5-9f0a-94a840dff107.jpg)

mode: dpi, font-size: large
![dpi_large](https://cloud.githubusercontent.com/assets/11527966/11548287/88d1f1ba-990f-11e5-965c-b287c9855797.jpg)

mode: font, font-size: large
![font_large](https://cloud.githubusercontent.com/assets/11527966/11548290/952173e6-990f-11e5-87e0-41b488e86a45.jpg)

**Comment by lbross** [comment]
Was able to modify Edit Method screen to use the dpi and autosize settings. Appears to work okay now with dynamically generated fields. Also made changes to Profile Builder so it looks better with larger font sizes. Could not use autosize here because we share form between two different views. Will wait to format other forms until we see how this works. Dpi setting appears to help but still lots of work to move fields around.

**Comment by jdduh** [comment]
The eliminate dialog window looks good now. Please make the hru layer list a little wider. I still don't see the "Apply" button on BAGIS-H raster relass (discrete data) dialog, even after maximizing the window.

![rasterreclass_discretedata](https://cloud.githubusercontent.com/assets/11510708/11856330/b5048626-a404-11e5-8190-79989df9a6a0.JPG)

**Comment by lbross** [comment]
These changes have been made and there is a new version to download at
https://github.com/PSU-CSAR/vb-bagis-h/releases/tag/1.6.2.

Ran into some issues with merging between ebagis and master branches.
Hopefully resolved for now.

**Comment by jdduh** [comment]
Just did a more thorough review on the GUI. Here are the additional forms that need to be modified.

Several of the BAGIS-H template rule forms are not resizable, as a result, the apply and cancel buttons are not visible.

Readjust DAFlow dialog layout size.
![daflowgui](https://cloud.githubusercontent.com/assets/11510708/11885762/69060078-a4d7-11e5-9992-34d7104c86d1.JPG)

The layout on the landuse template rule needs to be adjusted.
![landusetemplaterule](https://cloud.githubusercontent.com/assets/11510708/11885771/768a28d2-a4d7-11e5-9b2f-b56069deb572.JPG)

Also, the Reclassify Zones tool needs some minor adjustment. I have tested the GUI by enlarging the font size to 150%.
![reclassifyzones](https://cloud.githubusercontent.com/assets/11510708/11885782/8b418504-a4d7-11e5-890a-3ddfbc08f285.JPG)

**Comment by jdduh** [comment]
BAGIS-P's method editor now looks good. Here are some additional GUI modification requests.

Timberline tool, the controls and texts are too crowded.
![timberlinetool](https://cloud.githubusercontent.com/assets/11510708/11885905/d0e0d2e4-a4d8-11e5-9f34-14873c3847e9.JPG)

Due to the very evolved steps in creating HRUs, NWCC folks end up with really long names for HRUs. Can you make the HRU name list wider (see circled objects). I notice that some controls show a popup message of the cell value. That seems to be a better solution if the width of the list cannot be enlarged further.
![parametersfromlayers](https://cloud.githubusercontent.com/assets/11510708/11885919/e8e0bae4-a4d8-11e5-8add-2ee7ebde7653.JPG)

**Comment by lbross** [comment]
Is the width of the HRU names list a problem in all of BAGIS-P? Or just on the parameter from layers tool? We can make it as wide as we need to. It just means the form will be wider which means there may be a scroll bar on the bottom of the form width exceeds the width of the screen.

**Comment by jdduh** [comment]
A scroll bar on the bottom would work too. Many of the list controls don't have the scroll bar available (see images below). The last image shows a different control that provides various ways of viewing the complete HRU names. There is no need to change the list to the grid control.

![listgui](https://cloud.githubusercontent.com/assets/11510708/11910453/c7c9a310-a5ab-11e5-9660-e657f2dd5653.JPG)

![listgui2](https://cloud.githubusercontent.com/assets/11510708/11910468/194b21b4-a5ac-11e5-9993-08e379a12780.JPG)

![listgui3](https://cloud.githubusercontent.com/assets/11510708/11910515/36a04acc-a5ad-11e5-86be-0c9f3555d48b.JPG)

**Comment by lbross** [comment]
Made the requested changes to BAGIS-P. Added horizontal scrollbar to hru
layer lists on Parameter Viewer, Export Parameters, and Parameter from
Layers forms. Posted new version of BAGIS-P add-in at
https://github.com/PSU-CSAR/vb-bagis-p/releases/tag/1.9.4.

Please test. If the scrollbar is an acceptable solution, I can implement on
BAGIS-H.

**Comment by jdduh** [comment]
The scroll bar works perfectly. Could you also enable the scroll bars on the following GUI?

![image](https://cloud.githubusercontent.com/assets/11510708/11969840/59e658a2-a8d5-11e5-86e3-5ba83b4db04f.png)

![image](https://cloud.githubusercontent.com/assets/11510708/11969847/75440810-a8d5-11e5-946c-9d99fa0cd19e.png)

![image](https://cloud.githubusercontent.com/assets/11510708/11969857/9023db74-a8d5-11e5-87cc-2555c527ae67.png)


For BAGIS-H:

![image](https://cloud.githubusercontent.com/assets/11510708/11969872/ca31bf84-a8d5-11e5-9acc-cfaf90507555.png)

![image](https://cloud.githubusercontent.com/assets/11510708/11969877/f2f04418-a8d5-11e5-96c3-35fb86ae4136.png)

![image](https://cloud.githubusercontent.com/assets/11510708/11969888/1742d736-a8d6-11e5-88d2-b6c72d24e1c3.png)

![image](https://cloud.githubusercontent.com/assets/11510708/11969894/38c5305c-a8d6-11e5-981f-0b485885235a.png)

**Comment by lbross** [comment]
I have added the scrollbars to the specified listboxes in BAGIS-H and
BAGIS-P. I also posted new versions of the add-ins to GitHub. It was a
small change so didn't update version numbers. Just use the latest.
