### ISSUE TITLE
AOI Download: Add search filter to basins aoi menu?

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis-h#24]
@jdduh: Do we want to add a search filter to the basins aoi menu (aoi download) screen on the PC client? Per PSU-CSAR/django-ebagis#28 available query fields are:

Contains:
Created/modified at
Created/modified after
Created/modified before
Created/modified range: 
Created by:

**Comment by jkeifer** [comment]
Note that per PSU-CSAR/django-ebagis#26, more filters are actually available. If you think of another parameter by which you'd want to search/filter, either give it a try or let me know and I can provide an example of what is supported.

**Comment by lbross** [comment]
1. Show AOI created by current user
2. Show AOI created within last 2 weeks, last month
3. Search for string within AOI name

**Comment by lbross** [comment]
Proposed UI for search filter on basins AOI menu. This is a Panel on the form that is toggled on/off using the show/hide filter button. The cancel button on the Panel also hides the filter. The List button will list all AOI's that meet the filter conditions. The default is to not use a filter. The clear filter button removes the filter conditions and adds all AOI's in the server database to the list. The apply filter button lists all AOI's that meet the filter conditions. Note that none of this is coded yet, this is how I envision it working. Thoughts?

![aoisearchfilter](https://cloud.githubusercontent.com/assets/11527966/15088272/4e5f362a-13a6-11e6-8539-fbf4d1995222.png)

**Comment by lbross** [comment]
@jkeifer Is there an endpoint for me to retrieve the current user name? If I am using a cached token, I won't have the user name. I can also cache the user name with the token if that makes more sense.

**Comment by jdduh** [comment]
A few questions about the GUI:
1. What's the default filter status? Unfiltered? 
2. Will the filter status be stored on the computer? What's its life cycle (scope)?

Please add a text/label box above the AOI list showing the filter status. You can use the texts in the filter dialog window as the label.

**Comment by jkeifer** [comment]
@lbross the valitdate-token endpoint response should include the username under the key `user`. However, I'd imagine you'd also want to cache the current user so you could show the user who they are and provide a logout button or something.

Just a note: logout, sometime way out in the future, should actually delete the token serverside. And tokens should be application/machine specific, so a user can log out of one instance but not another (I'd also provide a log out of all sessions function, like google et al. have). In fact, I'm going to make a low priority ticket for this: PSU-CSAR/django-ebagis#57.

**Comment by lbross** [comment]
Answers to questions from @jdduh 
1. The default filter status is unfiltered
2. Was not planning to store the filter status locally but we can. Current lifecycle is the only the life of the form. We could easily store it in the ArcMap session otherwise would be on disk. What would you like the lifecycle to be?
3. Will add label above the AOI list showing filter status
