### ISSUE TITLE
AOI Download: What to do following receipt of download.zip

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis-h#3]
What happens after the download.zip is received by PC-BAGIS? Should it be unzipped? Deleted?

**Comment by jdduh** [comment]
Unzipped and deleted.

**Comment by lbross** [comment]
The zip file will be unzipped in the same directory it was downloaded. The contents of the .zip file will be extracted into a folder with the same name as the .zip file. This should be the aoi name.
