### ISSUE TITLE
AOI Upload: Maximum length for comments field

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis-h#6]
Do we need an edit in PC-BAGIS so that the aoi comments field is not too long. Jarrett reports that their is no limitation on the database side but perhaps there are practical reasons for not letting it be too long?

**Comment by jdduh** [comment]
512 bytes

**Comment by lbross** [comment]
Leaving issue open until code changes are made

**Comment by lbross** [comment]
Fixed on eBAGIS branch
