### ISSUE TITLE
AOI Upload/Download: How to handle timeouts?

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/vb-bagis-h#8]
Uploading and downloading AOI's is an asynchronous process. In PC-BAGIS we use timer objects to poll the web service at 10 second intervals to update the status for the user. There are currently timeouts set to stop the timers if the process takes too long. Some large downloads/uploads could take a really long time. Is this the best approach?

I don't want to leave the timers running indefinitely. Would it make more sense to have a button for the user to click to poll the status for all submitted tasks, or ... ?

**Comment by jdduh** [comment]
What types of process status would trigger a timeout? If the process is still running on the server (e.g., compressing a huge AOI), then such a situation shouldn't trigger a timeout. I think eWSF has a similar UI to query the status of submitted requests. I don't think they have set a timeout threshold because some of their model calibration process could take weeks. I like the idea of allowing users to poll the status of all submitted tasks. Maybe we can provide a function to let users cancel submitted tasks - if we can figure out how to implement it.

**Comment by lbross** [comment]
The 3 types of process status I am aware of are PENDING, FAILURE, and SUCCESS. The process status of concern is PENDING. This is the status that has been returned when the processing queue gets "stuck". If the status is PENDING for longer than a selected time, PC-BAGIS triggers a timeout. The problem is that PC-BAGIS doesn't know if extended processing time is warranted or an error.

If we have the user trigger a query for the status of submitted requests, I am fine not having them timeout. I can change the design of PC-BAGIS. But if PC-BAGIS is programatically polling the status of each request and updating the UI at a regular interval, we should have a timeout. I'm worried about having too many timer objects running indefinitely.

**Comment by jkeifer** [comment]
Note that the PENDING status should have never been associated with a
failed upload/download. Even when the task processor isn't running properly
the tasks will still accumulate in the queue with a status of PENDING and
will be processed as soon as the task processor is running again. So all of
your download requests that timed out should have been processed once
Celery restarted.

Also, there are other task statuses, though I've never seen them myself.
Check the Celery docs for more information. I will at some point also take
a closer look to make sure everything is configured properly, as I think
the tasks should be getting some of the other statuses, such as STARTED.

**Comment by jkeifer** [comment]
I found out that the `STARTED` state is not enabled by default. I have enabled it on my dev branch and will update this thread when that change is merged into master and deployed to the test instance. See PSU-CSAR/django-ebagis-site#14 for more info.

**Comment by jkeifer** [comment]
I have merged the `STARTED` state change into master and it has been deployed. I have not tested it however, so let me know if you have any issues.

**Comment by lbross** [comment]
Can you confirm the state path for a task if it completes successfully? My guess is: PENDING -> STARTED -> SUCCESS.

And is this true for all tasks submitted to the service?

Changes will need to be made to PC-BAGIS to handle this new status.

**Comment by jkeifer** [comment]
That is correct, a task completes successfully via the state path you provided. And yes, all tasks run by celery should now use the `STARTED` state.

Hopefully this new status is helpful; if not I can easily revert it. Please let me know.

**Comment by lbross** [comment]
It is helpful. That last sentence was more of a ToDo for me than anything else.

**Comment by lbross** [comment]
Add a refresh button to check status and remove timers for each task. Need to cache information about any tasks in process when user quits ArcMap and restore when they go back in if desired.

**Comment by lbross** [comment]
![aoi_menu_3](https://cloud.githubusercontent.com/assets/11527966/10500746/6e60148e-728f-11e5-9bce-f9070e65e010.png)

Current screenshot of PC-BAGIS if you want to share with NWCC. Both uploads and downloads are working.

**Comment by lbross** [comment]
Closing. Will handle cancellation of tasks under issue #13
